/* CREATES TABLE DUCKS */
CREATE TABLE table_duck (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100),
	show VARCHAR(100),
	studio VARCHAR(100),
	notes TEXT
);

/* IMPORTS ALL DATA FROM CSV FILE*/
COPY table_duck(name, show, studio, notes)
FROM 'C:\list-of-fictional-ducks-in-animation-wikipedia.csv'
DELIMITER ','
CSV HEADER;